//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdhesionCoefficient
{
    using System;
    using System.Collections.Generic;
    
    public partial class adhesion_rules
    {
        public decimal id_rule { get; set; }
        public string rule { get; set; }
        public double precent_of_value { get; set; }
        public string percent_sign { get; set; }
    }
}
