//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdhesionCoefficient
{
    using System;
    using System.Collections.Generic;
    
    public partial class loco_type
    {
        public loco_type()
        {
            this.loco_adhesion_coeff = new HashSet<loco_adhesion_coeff>();
        }
    
        public decimal id_type { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<loco_adhesion_coeff> loco_adhesion_coeff { get; set; }
    }
}
