//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdhesionCoefficient
{
    using System;
    using System.Collections.Generic;
    
    public partial class loco_adhesion_coeff
    {
        public decimal id_loco { get; set; }
        public string loco_name { get; set; }
        public Nullable<decimal> id_loco_type { get; set; }
        public double adh_initial_coeff { get; set; }
    
        public virtual loco_type loco_type { get; set; }
    }
}
